//! FILENAME: app/src/core/lib/globalInputListeners.ts
// PURPOSE: The CENSUS that goes with the pointer-claim rule: every listener in
//          this app that binds a key or pointer event on `window` or `document`,
//          and what each one does about a claim.
//
// WHY IT EXISTS
//   `pointerClaims.ts` next door states the rule, and Core honours it at three
//   doors — mousedown, double-click, and both key handlers. Twice now that was
//   believed to be the whole story, and twice a fourth door turned up in a layer
//   nobody had enumerated. The last one was `api/keybindings.ts`: a CAPTURE-phase
//   `window` keydown, which is the OUTERMOST position in the document. It ran
//   before every Core door and called preventDefault()+stopPropagation(), so
//   Core's careful guards were never consulted at all. Measured, with a card
//   carrying `data-pointer-claim` inside `[data-focus-container="spreadsheet"]`:
//   Delete with a `<select>` focused executed `core.edit.clearContents` — the
//   user's selected CELLS were cleared — and Ctrl+V inside a claimed plain
//   `<input>` executed `core.clipboard.paste` AND cancelled the native paste into
//   the field, so even the one widget type Core's tag list certifies as working
//   was broken.
//
//   A door nobody has listed is a door nobody has checked. So the list is here,
//   it is complete by construction, and `globalInputListeners.test.ts` fails the
//   build when a listener exists that is not in it.
//
// >>> ADDING A `window.` OR `document.` LISTENER FOR A KEY OR POINTER EVENT?  <<<
// >>> ADD A ROW HERE IN THE SAME COMMIT. The drift test will make you.        <<<
//
// HOW TO PICK A VERDICT
//   Ask ONE question first: does this listener ACT — change document or grid
//   state, run a command, or call preventDefault — or does it merely OBSERVE?
//   An observer needs no guard. An actor needs one of the four other verdicts,
//   and "session-scoped" is a claim about LIFETIME that has to be true.
//
//   claim-guarded      Acts on the grid or the document from a gesture that
//                      could land inside a claimed surface. Consults
//                      `isKeyClaimed` / `isPointerClaimed` (or, for the
//                      dispatcher, folds the claim into the questions it already
//                      asks). ENFORCED: the test requires the file to reference
//                      one of those predicates.
//   app-global         Acts, and deliberately does NOT consult the claim,
//                      because the user wants it to work from inside a form too.
//                      Ctrl+S is the archetype: a blanket "a claim swallows every
//                      shortcut" would break Save. Keep this list short and
//                      keep every entry's reason in its note.
//   right-press-exempt Acts on the SECONDARY button, which `isPointerClaimed`
//                      never claims by design — an object's own context menu has
//                      to keep opening, or a claimant could trap the user inside
//                      its own rectangle with no way out. See `isPointerClaimed`.
//   session-scoped     Acts, but is registered only for the life of a gesture or
//                      a surface this same code began: the mousemove/mouseup of a
//                      drag whose mousedown was already filtered, or the
//                      Escape/click-outside of a popup it opened, which it uses
//                      only to close that popup. The lifetime IS the guard.
//   observes           Reads only. No state change, no command, no
//                      preventDefault.
//
// SCOPE
//   `window.addEventListener` / `document.addEventListener` for: keydown, keyup,
//   keypress, mousedown, mouseup, mousemove, click, dblclick, auxclick,
//   contextmenu, wheel, pointer*, touch*, dragover, dragstart, drop, paste, copy,
//   cut. Element-level listeners and React props are NOT in scope — they cannot
//   pre-empt a door they do not sit above. One row per FILE + EVENT (line numbers
//   churn; a file that binds the same event from two handlers gets one row whose
//   note says so).

/** What a listener does about a pointer claim. See "HOW TO PICK A VERDICT". */
export type GlobalListenerVerdict =
  | "claim-guarded"
  | "app-global"
  | "right-press-exempt"
  | "session-scoped"
  | "observes";

export interface GlobalInputListener {
  /** Path relative to `app/`. */
  file: string;
  /** The DOM event type bound. */
  event: string;
  verdict: GlobalListenerVerdict;
  /** What it does, and why that verdict. */
  note: string;
}

/** The predicates a `claim-guarded` row must reference. */
export const CLAIM_PREDICATES = ["isKeyClaimed", "isPointerClaimed", "findPointerClaim"] as const;

export const GLOBAL_INPUT_LISTENERS: readonly GlobalInputListener[] = [
  { file: "extensions/_shared/cli/components/CliPanel.tsx", event: "mousemove", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live, so the press that started it was already filtered." },
  { file: "extensions/_shared/cli/components/CliPanel.tsx", event: "mouseup", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live." },
  { file: "extensions/_shared/components/AggregationMenu.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/_shared/components/AggregationMenu.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "extensions/_shared/components/DropZone.tsx", event: "mousemove", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live, so the press that started it was already filtered." },
  { file: "extensions/_shared/components/FieldPillMenu.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/_shared/components/FieldPillMenu.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "extensions/_shared/components/FilterDropdown.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/_shared/components/FilterDropdown.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "extensions/_shared/components/TableFieldList.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/_shared/components/TableFieldList.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "extensions/_shared/components/useDragDrop.ts", event: "mousemove", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live, so the press that started it was already filtered." },
  { file: "extensions/_shared/components/useDragDrop.ts", event: "mouseup", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live." },
  { file: "extensions/_shared/components/ValueFieldContextMenu.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/_shared/components/ValueFieldContextMenu.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "extensions/_shared/lib/objectWheelScroll.ts", event: "wheel", verdict: "claim-guarded",
    note: "Scrolls the content of a registered floating object (a canvas pivot box, a floating range whose content reaches past its window) under the pointer; ONE shared listener for every target, on canvases and worksheets alike; topmost hit wins; preventDefault only when an overflowing axis is scrolled." },
  { file: "extensions/AutoFilter/components/FilterDropdownOverlay.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/AutoFilter/components/FilterDropdownOverlay.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "extensions/BuiltIn/CellBookmarks/index.ts", event: "keydown", verdict: "claim-guarded",
    note: "Ctrl+Shift+V OFF the grid opens the Save Current View overlay (on the grid the key is Paste Special's registry binding); it stays native inside a field or a cell edit. Its other keys (Ctrl+Shift+B, Ctrl+] / Ctrl+[) are registry bindings now, not this listener." },
  { file: "extensions/BuiltIn/FormatPainter/formatPainterLogic.ts", event: "mousemove", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live, so the press that started it was already filtered." },
  { file: "extensions/BuiltIn/FormatPainter/formatPainterLogic.ts", event: "mouseup", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live." },
  { file: "extensions/BuiltIn/FormatPainter/index.ts", event: "keydown", verdict: "app-global",
    note: "Escape ONLY: it deactivates the painter and acts only when the painter is already active — a mode the user entered on purpose and must be able to leave from anywhere, so it consults no claim. Ctrl+Shift+C is not this listener's (BUG-0199): the registry's core.formatPainter binding (not-editing) starts the painter, once." },
  { file: "extensions/BuiltIn/FormulaAutocomplete/FormulaAutocompleteOverlay.tsx", event: "mousemove", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live, so the press that started it was already filtered." },
  { file: "extensions/BuiltIn/FormulaAutocomplete/FormulaAutocompleteOverlay.tsx", event: "mouseup", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live." },
  { file: "extensions/BuiltIn/HomeTab/components/HomeTabCustomizeDialog.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/BuiltIn/ObjectPosition/components/GripMenu.tsx", event: "keydown", verdict: "session-scoped",
    note: "The grip's menu (BUG-0258 phase 5b), bound only while the menu Core's grip click opened is mounted: Escape closes it, ArrowUp/ArrowDown/Home/End move between its rows, Enter/Space run the active row -- each consumed, and it acts only on its own menu (a row it runs opens Size and Position or acts on the grip's object). For exactly the life of this listener it marks itself open (@api/objectPosition noteObjectGripMenuOpen), so the slicer and timeline keyboards -- window capture, which runs BEFORE this document-capture listener -- stand down on isObjectGripMenuOpen (M8 S7)." },
  { file: "extensions/BuiltIn/ObjectPosition/components/GripMenu.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for the grip's menu, bound (after the opening click) only while it is mounted; it closes only that menu." },
  { file: "extensions/BuiltIn/StatusBarAggregation/AggregationContextMenu.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/BuiltIn/StatusBarAggregation/AggregationContextMenu.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "extensions/BuiltIn/ZoomSlider/ZoomPresetMenu.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/BuiltIn/ZoomSlider/ZoomPresetMenu.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "extensions/CalculationOptions/components/CalculationStatusItem.tsx", event: "keydown", verdict: "app-global",
    note: "Escape / Ctrl+Break cancels a RUNNING recalculation; installed only while one is in flight. Cancelling from inside a form is the point." },
  { file: "extensions/CanvasSheet/lib/marquee.ts", event: "mousemove", verdict: "session-scoped",
    note: "Canvas marquee band: bound only by a left press on the EMPTY page (Core's background press, which already passed every door) and removed at that gesture's mouseup; it only grows the band." },
  { file: "extensions/CanvasSheet/lib/marquee.ts", event: "mouseup", verdict: "session-scoped",
    note: "Canvas marquee band: ends the band gesture its own background press began and selects what the band touched; removed by itself." },
  { file: "extensions/CanvasSheet/lib/objectNudge.ts", event: "keyup", verdict: "session-scoped",
    note: "Canvas arrow-key nudge: bound when a nudge BURST starts (a registry keybinding whose guard already required a canvas, grid focus and no inner owner of the arrows) and removed when that burst commits; an arrow's release only commits the burst's previewed geometry as one undo step." },
  { file: "extensions/Charts/components/AxisContextMenu.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/Charts/components/AxisContextMenu.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "extensions/Charts/components/ChartContextMenu.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/Charts/components/ChartContextMenu.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "extensions/Charts/components/ChartSpecEditorApp.tsx", event: "mousemove", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live, so the press that started it was already filtered." },
  { file: "extensions/Charts/components/ChartSpecEditorApp.tsx", event: "mouseup", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live." },
  { file: "extensions/Charts/components/QuickAccessPopup.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/Charts/components/QuickAccessPopup.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "extensions/Charts/components/tabs/SpecTab.tsx", event: "mousemove", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live, so the press that started it was already filtered." },
  { file: "extensions/Charts/components/tabs/SpecTab.tsx", event: "mouseup", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live." },
  { file: "extensions/Charts/index.ts", event: "contextmenu", verdict: "right-press-exempt",
    note: "Opens the chart's own menu. `isPointerClaimed` deliberately never claims SECONDARY_MOUSE_BUTTON so an object's context menu still opens; guarding this with the CLAIM would be the trap the exemption exists to prevent. Two guards that are not the claim were missing and are now there: a right-click whose target is an INPUT/TEXTAREA/SELECT/contentEditable is that field's (the overlay text editor mounts a <textarea> over a chart title, and its paste menu was being replaced by the chart's), and a right-click outside the grid container's own box is nobody's chart — the chart REGION is not clipped to the visible canvas, so a chart wider than a task-pane-narrowed grid matched clicks inside the pane." },
  { file: "extensions/Charts/index.ts", event: "keydown", verdict: "claim-guarded",
    note: "THREE handlers, one row (file + event). (1) Delete/Backspace removes the selected chart, or just its selected furniture. (2) plain Left/Right steps the insight overlay's points of interest. (3) the arrows walk the chart's element groups and members, and Escape steps one level up. Each door asks `isKeyClaimed` here AND `chartOwnsKeystroke` (Charts/handlers/selectionHandler.ts), which asks the claim again plus `isGridFocused` — a claim is a grid-overlay concept, so a focused <button> in the Format pane or on the ribbon carries none, and with only the claim and a tag list Delete from inside the chart's own pane DESTROYED THE CHART. Arrow precedence between (2) and (3) is one pure rule, `arrowsBelongToOverlayStep`, that both read. Ctrl+1 is NOT here: it goes through the keybinding registry with a `when` predicate, because that listener pre-empts this one." },
  { file: "extensions/Charts/index.ts", event: "mousemove", verdict: "observes",
    note: "Bound for the extension's life (it is NOT a drag session): tracks the pointer for chart tooltips and hover state (the POINTER is Core's, from the chart's zone answer); while an interval brush this file began from Core's content press (floatingObject:bodyDragStart) is live, it also moves that brush's marquee -- a transient preview, no write; and a move with the primary button UP drops a held button press whose release was never heard (it then acts on nothing). Never preventDefaults." },
  { file: "extensions/Charts/index.ts", event: "mouseup", verdict: "session-scoped",
    note: "Press-scoped (M5 T4): bound by Core's filtered press on a chart (floatingObject:selected, which may arm the pending sub-selection click; a 'grip' press arms none) and by a CONTENT press (floatingObject:bodyDragStart: the brush, or one of the chart's own buttons -- quick-access, pivot field, widget control -- BUG-0258 phase 4b); it unbinds itself at the first mouseup after it -- that press's release -- and finalizes the brush, acts on the button ONLY when released over the same button (lib/chartButtonPress.ts) where no other object covers it, or completes the click; the button press's Escape / blur live in lib/chartButtonSession.ts. A release of another button (a middle press) ends a brush with nothing selected. It used to be bound for the extension's whole life. chartMouseupLifetime.test.ts pins the shape, chartButtonRelease.test.ts the release." },
  { file: "extensions/Charts/lib/chartButtonSession.ts", event: "keydown", verdict: "session-scoped",
    note: "Escape cancels a press on one of a chart's own buttons (quick-access, pivot field, widget control) that index.ts began from Core's filtered content press (floatingObject:bodyDragStart), with nothing done; bound at that press, removed at its release, Escape, blur, a lost release, the next press or the extension's deactivation (BUG-0258 M7 review). Capture phase, and it stops only the Escape, only while the press is held; the chart's object-selection provider owns Escape meanwhile so a canvas does not also deselect the chart." },
  { file: "extensions/Checkbox/index.ts", event: "mousemove", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live, so the press that started it was already filtered." },
  { file: "extensions/Consolidate/components/ConsolidateDialog.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/Controls/components/ControlContextMenu.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/Controls/components/ControlContextMenu.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "extensions/Controls/index.ts", event: "keydown", verdict: "claim-guarded",
    note: "Two handlers: Delete removes the selected floating controls, and Ctrl+C/V/D/G copy, paste, duplicate and group them. Both had only the tag list." },
  { file: "extensions/Controls/index.ts", event: "mousemove", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live, so the press that started it was already filtered." },
  { file: "extensions/Controls/lib/buttonPress.ts", event: "keydown", verdict: "session-scoped",
    note: "Escape cancels a run-mode floating button press this file itself began, running nothing; bound at the press Core handed over (floatingObject:bodyDragStart, part 'button'), removed at its release, Escape, blur, a lost release, the next press or the extension's deactivation. Capture phase, and it stops only the Escape, only while the press is held; Controls' object-selection provider owns Escape meanwhile so a canvas does not also deselect the button." },
  { file: "extensions/Controls/lib/buttonPress.ts", event: "mousemove", verdict: "session-scoped",
    note: "Press session (BUG-0258 phase 4c): bound only while a run-mode button press this file began from Core's filtered press is held. It turns the pressed look on and off as the pointer enters and leaves the button, and ends the press, running nothing, when the primary button is UP (a release this page never heard); it writes nothing." },
  { file: "extensions/Controls/lib/buttonPress.ts", event: "mouseup", verdict: "session-scoped",
    note: "Press session (BUG-0258 phase 4c): the release of a run-mode button press this file began; the button runs (button:clicked, then the M4 click path) ONLY when released inside it -- on its rectangle and the topmost floating object there -- and the listener unbinds itself. A release of another button ends the press, running nothing, when the primary one is up (a middle press)." },
  { file: "extensions/Controls/lib/controlObjectMenu.ts", event: "contextmenu", verdict: "right-press-exempt",
    note: "The M3a control object menu. Same exemption." },
  { file: "extensions/CustomFillLists/components/CustomFillListsDialog.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/DataForm/components/DataFormDialog.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/DataTables/components/DataTableDialog.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/DataValidation/components/ListDropdownOverlay.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "extensions/DataValidation/handlers/keyboardHandler.ts", event: "keydown", verdict: "claim-guarded",
    note: "Alt+Down opens the ACTIVE CELL's in-cell list — a grid gesture aimed at a cell the user is not looking at." },
  { file: "extensions/DefinedNames/components/NameManagerDialog.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/DefinedNames/components/NameManagerDialog.tsx", event: "mousemove", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live, so the press that started it was already filtered." },
  { file: "extensions/DefinedNames/components/NameManagerDialog.tsx", event: "mouseup", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live." },
  { file: "extensions/DefinedNames/components/NewFunctionDialog.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/DefinedNames/components/NewNameDialog.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/EvaluateFormula/components/EvaluateFormulaDialog.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/FileExplorer/FileExplorerView.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "extensions/FileExplorer/FileExplorerView.tsx", event: "mousemove", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live, so the press that started it was already filtered." },
  { file: "extensions/FileExplorer/FileExplorerView.tsx", event: "mouseup", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live." },
  { file: "extensions/FloatingRange/components/FloatingRangeContextMenu.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/FloatingRange/components/FloatingRangeContextMenu.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "extensions/FloatingRange/index.ts", event: "contextmenu", verdict: "right-press-exempt",
    note: "The Floating Range menu. Same exemption." },
  { file: "extensions/FloatingRange/index.ts", event: "keydown", verdict: "claim-guarded",
    note: "Arrows move the floating range's local selection, Delete clears its cells or deletes the object, a printable key opens its editor." },
  { file: "extensions/FloatingRange/index.ts", event: "mousemove", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live, so the press that started it was already filtered." },
  { file: "extensions/FloatingRange/index.ts", event: "mouseup", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live." },
  { file: "extensions/FloatingRange/lib/frMove.ts", event: "mouseup", verdict: "session-scoped",
    note: "Move session: armed by the first movePreview of a Core move of a floating range (whose press Core already filtered) and removed at that gesture's mouseup; it only puts back a preview no moveComplete followed." },
  { file: "extensions/FormulaVisualizer/components/FormulaVisualizer.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/GoalSeek/components/GoalSeekDialog.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/Grouping/components/GroupSettingsDialog.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/Grouping/index.ts", event: "mousedown", verdict: "claim-guarded",
    note: "Outline-bar press, hit-tested by CLIENT POINT against the canvas; +/- collapse mutates the document." },
  { file: "extensions/Hyperlinks/InsertHyperlinkDialog.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/MacroRecorder/components/MacroLibraryDialog.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/MacroRecorder/components/RecordedMacroDialog.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/MacroRecorder/components/StartRecordingDialog.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/MacroRecorder/index.ts", event: "keydown", verdict: "app-global",
    note: "Ctrl+Shift+R starts/stops recording. Stopping a recording from inside a form is exactly right." },
  { file: "extensions/ModelEditor/components/CliReferencePane.tsx", event: "mousemove", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live, so the press that started it was already filtered." },
  { file: "extensions/ModelEditor/components/CliReferencePane.tsx", event: "mouseup", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live." },
  { file: "extensions/ModelEditor/components/ModelEditorApp.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/ModelEditor/components/TopBarMenu.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a menu this surface itself opened; registered only while it is open." },
  { file: "extensions/ModelEditor/components/TopBarMenu.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape for a menu this surface itself opened; registered only while it is open, and it stops propagation so an outer dialog does not close with it." },
  { file: "extensions/ModelEditor/components/sections/CalcGroupsSection.tsx", event: "click", verdict: "session-scoped",
    note: "Click-outside dismissal for a menu this surface itself opened." },
  { file: "extensions/ModelEditor/components/sections/CalcGroupsSection.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/ModelEditor/components/sections/ExpressionWorkspace.tsx", event: "mousemove", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live, so the press that started it was already filtered." },
  { file: "extensions/ModelEditor/components/sections/ExpressionWorkspace.tsx", event: "mouseup", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live." },
  { file: "extensions/ModelEditor/components/sections/MeasuresSection.tsx", event: "click", verdict: "session-scoped",
    note: "Click-outside dismissal for a menu this surface itself opened." },
  { file: "extensions/ModelEditor/components/sections/MeasuresSection.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/Pivot/components/PivotHeaderFilterDropdown.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/Pivot/components/PivotHeaderFilterDropdown.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "extensions/Pivot/components/SortDropdown.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/Pivot/components/SortDropdown.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "extensions/Pivot/index.ts", event: "mousemove", verdict: "observes",
    note: "Bound for the extension's life (document; it is NOT a drag session): hover state only -- the worksheet pivot's filter-dropdown highlight, and the canvas pivot box's chrome highlight (updatePivotVisualHoverAt: set over the TOPMOST box's chrome, cleared elsewhere). Never preventDefaults." },
  { file: "extensions/Pivot/lib/pivotChromePress.ts", event: "keydown", verdict: "session-scoped",
    note: "Escape cancels a canvas pivot box chrome press (+/-, report filter, Row/Column Labels button, Cancel) this file itself began, with no action; bound at the press Core handed over (floatingObject:bodyDragStart), removed at its release, Escape, blur, a lost release, the next press or the box's teardown. Capture phase, and it stops only the Escape, only while the press is held; the box's object-selection provider owns Escape meanwhile so a canvas does not also deselect the box." },
  { file: "extensions/Pivot/lib/pivotChromePress.ts", event: "mousemove", verdict: "session-scoped",
    note: "Press session (BUG-0258 phase 4, D5): bound only while a pivot box chrome press this file began from Core's filtered press is held. It only ends that press, with no action, when the primary button is UP (a release this page never heard); it writes nothing." },
  { file: "extensions/Pivot/lib/pivotChromePress.ts", event: "mouseup", verdict: "session-scoped",
    note: "Press session (BUG-0258 phase 4, D5): the release of a pivot box chrome press this file began; the chrome acts (handlePivotVisualPress, with its 450 ms double-click guard) ONLY when released over the same piece of chrome where no other object covers the box, and the listener unbinds itself. A release of another button ends the press, acting on nothing, when the primary one is up (a middle press)." },
  { file: "extensions/Pivot/lib/pivotVisualContextMenu.ts", event: "keydown", verdict: "session-scoped",
    note: "Escape for the canvas pivot box's own right-click menu, registered only while that menu is open; it closes only its own surface." },
  { file: "extensions/Pivot/lib/pivotVisualContextMenu.ts", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for the canvas pivot box menu this surface itself opened; it closes only its own surface." },
  { file: "extensions/Pivot/lib/pivotVisualOverlay.ts", event: "contextmenu", verdict: "right-press-exempt",
    note: "Canvas pivot box menu (Slicer precedent). Same exemption; claims only when a pivot box is the topmost floating object." },
  { file: "extensions/RemoveDuplicates/components/RemoveDuplicatesDialog.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/Review/components/CommentPanelOverlay.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "extensions/Review/components/NoteEditorOverlay.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "extensions/Review/components/NoteEditorOverlay.tsx", event: "mousemove", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live, so the press that started it was already filtered." },
  { file: "extensions/Review/components/NoteEditorOverlay.tsx", event: "mouseup", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live." },
  { file: "extensions/Review/handlers/hoverHandler.ts", event: "mousemove", verdict: "observes",
    note: "Comment-indicator hover state. Never preventDefaults." },
  { file: "extensions/Review/handlers/hoverHandler.ts", event: "wheel", verdict: "observes",
    note: "Passive listener that only clears hover state." },
  { file: "extensions/ScenarioManager/components/ScenarioManagerDialog.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/ScenarioManager/components/ScenarioSummaryDialog.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/ScriptableObjects/components/CodeEditorDialog.tsx", event: "mousemove", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live, so the press that started it was already filtered." },
  { file: "extensions/ScriptableObjects/components/CodeEditorDialog.tsx", event: "mouseup", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live." },
  { file: "extensions/ScriptableObjects/components/ObjectScriptEditorApp.tsx", event: "mousemove", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live, so the press that started it was already filtered." },
  { file: "extensions/ScriptableObjects/components/ObjectScriptEditorApp.tsx", event: "mouseup", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live." },
  { file: "extensions/Slicer/handlers/slicerContextMenu.ts", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/Slicer/handlers/slicerContextMenu.ts", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "extensions/Slicer/index.ts", event: "contextmenu", verdict: "right-press-exempt",
    note: "Slicer menu. Same exemption." },
  { file: "extensions/Slicer/index.ts", event: "mouseup", verdict: "session-scoped",
    note: "Frame click, press-scoped (M5 T4; BUG-0258 phase 4): bound by Core's filtered press on a slicer (floatingObject:selected arms the pending click and binds it; a 'grip' press arms nothing), removed by the first mouseup after it -- that press's release. It only narrows a kept multi-selection to the slicer pressed; it reads no point and commits nothing (every item, Select all, clear button and scrollbar press is the content gesture's, lib/slicerItemDrag.ts, which TAKES the pending click at floatingObject:bodyDragStart). Core has already ended a frame move (moveComplete clears the pending click) before it hears the release. slicerMouseupLifetime.test.ts pins the shape." },
  { file: "extensions/Slicer/index.ts", event: "wheel", verdict: "claim-guarded",
    note: "Scrolls a slicer's item list, chosen by client-point hit test over the canvas; preventDefault." },
  { file: "extensions/Slicer/lib/slicerItemDrag.ts", event: "keydown", verdict: "session-scoped",
    note: "Escape cancels the slicer content gesture (an item click or run drag, a Select all / clear button press, a scrollbar drag) this file itself began, with no commit; bound at the press Core handed over (floatingObject:bodyDragStart), removed at its release, Escape, blur or a lost release. Capture phase, and it stops only the Escape, only while the gesture lives; the slicer's object-selection provider owns Escape meanwhile so a canvas does not also deselect the slicer." },
  { file: "extensions/Slicer/lib/slicerItemDrag.ts", event: "mousemove", verdict: "session-scoped",
    note: "Drag session (BUG-0258 phase 4): bound only while a slicer content gesture this file began from Core's filtered press is live. It moves a TRANSIENT run preview or the item scroll only (no backend write), and a move with the primary button UP ends the gesture with no commit -- the phantom drag slicerNoPhantomDrag.test.ts scans for." },
  { file: "extensions/Slicer/lib/slicerItemDrag.ts", event: "mouseup", verdict: "session-scoped",
    note: "Drag session (BUG-0258 phase 4): the release of a slicer content gesture this file began; makes the ONE queued commit (an item click with Core's raw Ctrl, a run, or a clear when a button is released over itself where no other object covers it) and unbinds itself. A release of another button ends the gesture with no commit when the primary one is up (a middle press)." },
  { file: "extensions/Slicer/lib/slicerKeys.ts", event: "keydown", verdict: "claim-guarded",
    note: "The keyboard INSIDE a selected slicer (M8 S7): window capture, for the extension's life. It claims nothing until Enter went into the ONE selected object, a slicer (then the arrows/Home/End/PageUp/PageDown move a focus ring, Space/Enter apply with the slicer's click rules, Escape leaves; Tab is never claimed) -- except Alt+C on a single selected, FILTERED slicer, which clears its filter. While inside on a worksheet it CLAIMS the selection (@api/selectionOwner, id slicerKeyFocus, receivesTyping false), so Core's doors -- type-to-edit, Delete, Alt+Down -- refuse rather than act on the active cell hidden behind the slicer (M8 review finding 1); a key that finds the focus stale (its items gone, unannounced) ends it, says so, and is consumed except Tab. Stands down, in order, on isKeyClaimed, defaultPrevented (the dispatcher took it -- a user's own binding on Space, Enter or an arrow included, which since M8 S9 can be bound to Space too), an INPUT/TEXTAREA/contentEditable target, a live cell edit (isCellEditInProgress: Core's own or a floating grid's external session, parked or not), the grid not focused, a live slicer content gesture, the slicer's menu open (isSlicerContextMenuOpen) and an object's grip menu open (isObjectGripMenuOpen). A claimed key gets preventDefault + stopPropagation even at the edge, so the grid's bubble listeners never see it." },
  { file: "extensions/Slicer/lib/slicerKeys.ts", event: "mousedown", verdict: "observes",
    note: "Ends the keyboard's INNER focus in a slicer (view state only) on a RIGHT press anywhere but that slicer -- another object's or the grid's menu opens without changing the selection, and its Escape is then the menu's (M8 review finding 7). Window capture, bound only while the keyboard is inside (going in binds it, leaving removes it -- activate() binds no mousedown); reads the button and the point, never a modifier; changes no document or grid state, runs no command, never calls preventDefault." },
  { file: "extensions/Solver/components/SolverDialog.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/Solver/components/SolverResultDialog.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/Sorting/components/SortDialog.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/Sorting/components/SortOptionsPopup.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/Sparklines/components/CreateSparklineDialog.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "extensions/TextToColumns/components/TextToColumnsDialog.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "extensions/TimelineSlicer/handlers/timelineSlicerContextMenu.ts", event: "keydown", verdict: "session-scoped",
    note: "Escape closes the timeline's own right-click menu and is consumed (document capture, bound while the menu is open, removed on every way it closes -- BUG-0270 review; before it the menu had no key handling and Escape deselected the timeline behind it). The dispatcher's Escape bindings stand down meanwhile: the timeline's provider owns Escape and Delete while the menu is open." },
  { file: "extensions/TimelineSlicer/handlers/timelineSlicerContextMenu.ts", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "extensions/TimelineSlicer/index.ts", event: "contextmenu", verdict: "right-press-exempt",
    note: "Timeline slicer menu. Same exemption." },
  { file: "extensions/TimelineSlicer/index.ts", event: "mouseup", verdict: "session-scoped",
    note: "Frame click (BUG-0258): bound by Core's filtered press on a timeline (floatingObject:selected arms the pending click and binds it), removed by the first mouseup after it -- that press's release. It only narrows a kept multi-selection to the timeline pressed; it commits nothing and reads no point (every period, range-end and button click is the content gesture's, which TAKES the pending click at floatingObject:bodyDragStart). timelineNoPhantomDrag.test.ts pins the lifetime and scans what it reaches." },
  { file: "extensions/TimelineSlicer/index.ts", event: "wheel", verdict: "claim-guarded",
    note: "Same as Slicer: client-point hit test, preventDefault." },
  { file: "extensions/TimelineSlicer/lib/timelineKeys.ts", event: "keydown", verdict: "claim-guarded",
    note: "The keyboard INSIDE a selected timeline (M8 S8): window capture, for the extension's life. It claims nothing until Enter went into the ONE selected object, a timeline (then Left/Right/Home/End/PageUp/PageDown move a focus ring between the periods, with Shift they grow a TRANSIENT preview, Space/Enter commit ONE range through the range drag's commit rule, Up/Down are consumed and inert, Escape drops the preview and then leaves; Tab is never claimed) -- except Alt+C on a single selected, filtered timeline, which clears its filter. While inside on a worksheet it CLAIMS the selection (@api/selectionOwner, id timelineKeyFocus, receivesTyping false), so Core's doors -- type-to-edit, Delete, Alt+Down -- refuse rather than act on the active cell hidden behind the timeline (M8 review finding 1); a key that finds the focus stale (a level change or its period gone, unannounced) ends it, says so, and is consumed except Tab and an Enter that goes in again. Stands down, in order, on isKeyClaimed, defaultPrevented (the dispatcher -- a user's own binding on Space, Enter or an arrow included, M8 S9 -- or the Slicer's keyboard took it), an INPUT/TEXTAREA/contentEditable target, a live cell edit (isCellEditInProgress: Core's own or a floating grid's external session, parked or not), the grid not focused, a live timeline content gesture, the timeline's menu open (isTimelineContextMenuOpen) and an object's grip menu open (isObjectGripMenuOpen). A claimed key gets preventDefault + stopPropagation even at the edge, so the grid's bubble listeners never see it." },
  { file: "extensions/TimelineSlicer/lib/timelineKeys.ts", event: "mousedown", verdict: "observes",
    note: "Ends the keyboard's INNER focus in a timeline (view state only; its preview goes with it) on a RIGHT press anywhere but that timeline -- a slicer's menu opens without selecting the slicer, so the timeline stayed selected and its inside took the menu's Escape, Enter and Space (M8 review finding 7). Window capture, bound only while the keyboard is inside (going in binds it, leaving removes it -- activate() binds no mousedown); reads the button and the point, never a modifier; changes no document or grid state, runs no command, never calls preventDefault." },
  { file: "extensions/TimelineSlicer/lib/timelineRangeDrag.ts", event: "keydown", verdict: "session-scoped",
    note: "Escape cancels the timeline content gesture (range drag, button press, scrollbar drag) this file itself began, with no commit; bound at the press Core handed over (floatingObject:bodyDragStart), removed at its release, Escape, blur or a lost release. Capture phase, and it stops only the Escape, only while the gesture lives; the timeline's object-selection provider owns Escape meanwhile so a canvas does not also deselect the timeline." },
  { file: "extensions/TimelineSlicer/lib/timelineRangeDrag.ts", event: "mousemove", verdict: "session-scoped",
    note: "Drag session (BUG-0258): bound only while a timeline content gesture this file began from Core's filtered press is live. It moves a TRANSIENT preview only (no backend write), and a move with the primary button UP ends the gesture with no commit -- the phantom drag timelineNoPhantomDrag.test.ts scans for." },
  { file: "extensions/TimelineSlicer/lib/timelineRangeDrag.ts", event: "mouseup", verdict: "session-scoped",
    note: "Drag session (BUG-0258): the release of a timeline content gesture this file began; makes the ONE commit (a range, a clear, a level) and unbinds itself. A Shift+press on a period (the raw Shift Core hands the content on floatingObject:bodyDragStart; on content it never reaches object selection) makes that commit EXTEND the range shown instead of replacing it. A release of another button ends the gesture with no commit when the primary one is up (a middle press)." },
  { file: "extensions/WatchWindow/components/WatchWindowDialog.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "src/api/dialogLayout.tsx", event: "mousemove", verdict: "session-scoped",
    note: "Pane-divider drag: registered only while a drag this dialog's own splitter began is live, so the press that started it was already filtered." },
  { file: "src/api/dialogLayout.tsx", event: "mouseup", verdict: "session-scoped",
    note: "Pane-divider drag: registered only while a drag this dialog's own splitter began is live; it ends the drag and nothing else." },
  { file: "src/api/dialogWindow.tsx", event: "mousemove", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live, so the press that started it was already filtered." },
  { file: "src/api/dialogWindow.tsx", event: "mouseup", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live." },
  { file: "src/api/keybindings.ts", event: "keydown", verdict: "claim-guarded",
    note: "THE dispatcher. Window-CAPTURE, so it pre-empts all three Core doors. A claim makes it (a) not-grid-focused, so GRID_SCOPED_COMMANDS are refused, and (b) editing-equivalent, so context:'not-editing' is refused. A live CELL EDIT -- Core's own (in-cell editor, formula bar, or parked on another sheet with the keyboard on the grid container; read from core/lib/cellEditFlag.ts) or an external session -- does both, unprevented, wherever the keyboard is. Truly global bindings (Ctrl+S) still fire. Installed at init, so on window capture it runs BEFORE every extension's own window-capture keydown (FloatingRange, the slicer and timeline keyboards), which stand down on defaultPrevented. Space and '+' are matched by NAME ('Ctrl+Space', 'Ctrl+Plus', M8 S9): a user's binding on Ctrl+Space, Shift+Space, Ctrl+Shift+Space or Space takes the key before the grid's own Space handling, and findConflicts names that grid key in Settings; with nothing bound the keystroke is not touched." },
  { file: "src/api/layout/primitives/Launcher.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "src/api/layout/primitives/Launcher.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "src/api/layout/primitives/Popover.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "src/api/layout/primitives/Popover.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "src/api/layout/primitives/Tooltip.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape dismisses a tooltip this primitive itself opened, including one opened by hover while focus is elsewhere (WCAG 1.4.13). Registered only while that tooltip is open, never calls preventDefault, closes nothing but that tooltip." },
  { file: "src/api/objectSelection.ts", event: "mouseup", verdict: "session-scoped",
    note: "Press parity on a canvas: bound by Core's own object press (noteObjectPress, after the press passed every door) and removed at that press's mouseup; it only settles the object-selection set (narrow a kept multi-selection, drop a Ctrl/Shift-toggled member)." },
  { file: "src/core/components/Scrollbar/Scrollbar.tsx", event: "mousemove", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live, so the press that started it was already filtered." },
  { file: "src/core/components/Scrollbar/Scrollbar.tsx", event: "mouseup", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live." },
  { file: "src/core/components/Spreadsheet/useSpreadsheetLayout.ts", event: "keydown", verdict: "observes",
    note: "Schedules a repaint of the status-bar mode readout on the next frame. Reads nothing, changes nothing, never preventDefaults." },
  { file: "src/core/components/Spreadsheet/useSpreadsheetSelection.ts", event: "mousemove", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live, so the press that started it was already filtered." },
  { file: "src/core/components/Spreadsheet/useSpreadsheetSelection.ts", event: "mouseup", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live." },
  { file: "src/core/hooks/useMouseSelection/layout/overlayMoveHandlers.ts", event: "mouseup", verdict: "session-scoped",
    note: "Capture phase; bound by Core's own frame press when it arms a move, removed at that press's release (and a stale one, whose release never came, at the next arm); ends the move (moveComplete) before any family's bubble mouseup hears a release that landed outside the grid area." },
  { file: "src/core/hooks/useMouseSelection/useMouseSelection.ts", event: "keydown", verdict: "session-scoped",
    note: "Ctrl toggles move/copy and Escape cancels, for a SELECTION DRAG already in flight; registered only while isSelectionDragging, and that drag began at a mousedown gridPointerEntry had already filtered." },
  { file: "src/core/hooks/useMouseSelection/useMouseSelection.ts", event: "keyup", verdict: "observes",
    note: "Clears the Ctrl copy-mode flag; only installed while a selection drag is live." },
  { file: "src/core/hooks/useMouseSelection/useMouseSelection.ts", event: "mousedown", verdict: "observes",
    note: "Clears a latched-mouseup boolean so a finished gesture cannot end the next one." },
  { file: "src/core/hooks/useMouseSelection/useMouseSelection.ts", event: "mousemove", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live, so the press that started it was already filtered." },
  { file: "src/core/hooks/useMouseSelection/useMouseSelection.ts", event: "mouseup", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live." },
  { file: "src/core/lib/cellPressRelease.ts", event: "keydown", verdict: "session-scoped",
    note: "Escape ends a cell press this file itself holds (BUG-0258 phase 4: a cell click interceptor answered Core's FILTERED mouse-down -- useSpreadsheetSelection's door, after the pointer claim -- with a release claim), running nothing; bound at that press, removed at its release, Escape, blur, a lost release or the next press. Capture phase; it stops the Escape only once a claim holds the press -- while the interceptors are still answering it cancels and lets the key through." },
  { file: "src/core/lib/cellPressRelease.ts", event: "mousemove", verdict: "session-scoped",
    note: "Press session (BUG-0258 phase 4): bound only while a cell press Core's filtered mouse-down opened is held. It turns the claim's pressed look on and off as the pointer enters and leaves the target, and ends the press, running nothing, when the primary button is UP (a release this page never heard); it writes nothing." },
  { file: "src/core/lib/cellPressRelease.ts", event: "mouseup", verdict: "session-scoped",
    note: "Press session (BUG-0258 phase 4): the release of a cell press Core's filtered mouse-down opened; the claim (an in-cell button, a worksheet pivot's +/-, filter button or loading Cancel) runs ONLY when released over the same target, on the cells of the same sheet (never over a floating object, a claimed element or DOM above the grid), and the listener unbinds itself. A release of another button ends the press, running nothing, when the primary one is up (a middle press)." },
  { file: "src/core/lib/dialogs.ts", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "src/core/lib/overlayTextEditor.ts", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside commit for an in-place editor this seam itself opened: registered for the life of ONE session, ends only that session, and stands down while the session is expecting a formula reference, because that press is a PICK. It is on WINDOW and in CAPTURE because a press on the grid is preventDefault()ed, so the editor never loses focus and no blur ever arrives — without it, an editor whose Enter types a newline has no commit gesture at all." },
  { file: "src/modelEditorMain.tsx", event: "dragover", verdict: "app-global",
    note: "Separate Model Editor window; preventDefault stops the browser navigating away when a file is dropped. No grid, no claim." },
  { file: "src/modelEditorMain.tsx", event: "drop", verdict: "app-global",
    note: "As dragover: the Model Editor window swallows a stray file drop so the WebView does not navigate to it. No grid, no claim." },
  { file: "src/shell/ActivityBar/SidePanel.tsx", event: "mousemove", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live, so the press that started it was already filtered." },
  { file: "src/shell/ActivityBar/SidePanel.tsx", event: "mouseup", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live." },
  { file: "src/shell/DialogContainer.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "src/shell/FormulaBar/FormulaBar.tsx", event: "mousemove", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live, so the press that started it was already filtered." },
  { file: "src/shell/FormulaBar/FormulaBar.tsx", event: "mouseup", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live." },
  { file: "src/shell/FormulaBar/InsertFunctionDialog.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "src/shell/FormulaBar/NameBox.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "src/shell/FormulaBar/NameBoxDropdown.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "src/shell/FormulaBar/NameBoxDropdown.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "src/shell/MenuBar/MenuBar.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "src/shell/MenuBar/MenuBar.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "src/shell/Overlays/ContextMenu/ContextMenu.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "src/shell/Overlays/ContextMenu/ContextMenu.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "src/shell/Ribbon/PanelContextMenu.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape / arrow keys for a popup or dialog this surface itself opened; it acts only on its own surface." },
  { file: "src/shell/Ribbon/PanelContextMenu.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "src/shell/Ribbon/RibbonContainer.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "src/shell/SheetTabs/SheetTabs.tsx", event: "keydown", verdict: "session-scoped",
    note: "Escape closes the add-sheet kind menu (Worksheet / Canvas) this surface itself opened; registered only while that menu is open, and it acts only on it." },
  { file: "src/shell/SheetTabs/SheetTabs.tsx", event: "mousedown", verdict: "session-scoped",
    note: "Click-outside dismissal for a popup this surface itself opened; it closes only its own surface." },
  { file: "src/shell/SheetTabs/SheetTabs.tsx", event: "mousemove", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live, so the press that started it was already filtered." },
  { file: "src/shell/SheetTabs/SheetTabs.tsx", event: "mouseup", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live." },
  { file: "src/shell/TaskPane/TaskPaneContainer.tsx", event: "mousemove", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live, so the press that started it was already filtered." },
  { file: "src/shell/TaskPane/TaskPaneContainer.tsx", event: "mouseup", verdict: "session-scoped",
    note: "Drag session: registered only while a drag this surface itself began is live." },
];

/** Every listener that ACTS on a gesture that could land inside a claimed
 *  surface and therefore has to consult the claim. */
export function claimGuardedFiles(): string[] {
  return [
    ...new Set(
      GLOBAL_INPUT_LISTENERS.filter((l) => l.verdict === "claim-guarded").map((l) => l.file),
    ),
  ].sort();
}

/** Every verdict, in the order the header explains them. */
export const ALL_VERDICTS: readonly GlobalListenerVerdict[] = [
  "claim-guarded",
  "app-global",
  "right-press-exempt",
  "session-scoped",
  "observes",
];

/** Count by verdict — what the census says about itself, for the test's report. */
export function verdictCounts(): Record<GlobalListenerVerdict, number> {
  const out = {} as Record<GlobalListenerVerdict, number>;
  for (const v of ALL_VERDICTS) out[v] = 0;
  for (const l of GLOBAL_INPUT_LISTENERS) out[l.verdict] += 1;
  return out;
}
