//! FILENAME: app/extensions/ScriptEditor/lib/actionCodegen.ts
// PURPOSE: Turn recorded user actions into readable Calcula TypeScript — the
//          codegen half of the macro recorder (the customization on-ramp:
//          record, read the generated code, start editing).
// CONTEXT: Pure, dependency-free, unit-tested. v1 records cell edits; each
//          becomes a Calcula.setCellValue(...) call. The sheet index is carried
//          per action so a multi-sheet recording replays on the right sheets.

/** A recorded cell write, stamped with the sheet it happened on. */
export interface RecordedAction {
  /** 0-based row. */
  row: number;
  /** 0-based column. */
  col: number;
  /** The value the user entered (formula or literal, as a string). */
  value: string;
  /** 0-based sheet index the edit was made on. */
  sheetIndex: number;
}

/**
 * Generate a readable Calcula script from recorded actions. Each cell edit
 * becomes a `Calcula.setCellValue(row, col, value, sheetIndex)` call. Values are
 * JSON-encoded so quotes, backslashes, and newlines are escaped safely.
 */
export function generateMacroSource(actions: RecordedAction[]): string {
  const header =
    "// Recorded macro\n" +
    "// Generated by the Calcula macro recorder. Edit freely, then Run.\n\n";

  if (actions.length === 0) {
    return header + "// (no actions were recorded)\n";
  }

  const lines = actions.map(
    (a) =>
      `Calcula.setCellValue(${a.row}, ${a.col}, ${JSON.stringify(a.value)}, ${a.sheetIndex});`,
  );
  return header + lines.join("\n") + "\n";
}
