//! Reference documentation for the expression-language functions.
//!
//! The canonical docs live as one Markdown file per function under
//! `docs/functions/` in this repository, arranged in one category subfolder
//! per function group (e.g. `Aggregation Functions/SUM.md`). They are
//! embedded into the library at compile time by this crate's build script
//! (`build.rs`), so [`function_docs`] never touches the disk: hosts get the
//! full reference instantly, packaged builds work without the source tree,
//! and the docs are always exactly as fresh as the engine build they ship
//! with. Editing a doc file triggers regeneration on the next build
//! (`cargo:rerun-if-changed`).

/// One function's reference documentation: the function name (the file stem,
/// e.g. `"DIVIDE"`) and its raw Markdown body.
#[derive(Debug, Clone)]
pub struct FunctionDoc {
    pub name: String,
    pub markdown: String,
}

// `FUNCTION_DOCS: &[(&str, &str)]` — generated by build.rs from docs/functions.
include!(concat!(env!("OUT_DIR"), "/function_docs_generated.rs"));

/// Every embedded function doc, sorted by name.
pub fn function_docs() -> Vec<FunctionDoc> {
    FUNCTION_DOCS
        .iter()
        .map(|&(name, markdown)| FunctionDoc {
            name: name.to_string(),
            markdown: markdown.to_string(),
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embeds_the_function_docs() {
        let docs = function_docs();
        assert!(!docs.is_empty(), "docs must be embedded at build time");
        let abs = docs
            .iter()
            .find(|d| d.name == "ABS")
            .expect("ABS.md present");
        assert!(abs.markdown.contains("# ABS"));
        // Sorted by name.
        let mut sorted = docs.clone();
        sorted.sort_by(|a, b| a.name.cmp(&b.name));
        assert_eq!(
            docs.iter().map(|d| &d.name).collect::<Vec<_>>(),
            sorted.iter().map(|d| &d.name).collect::<Vec<_>>()
        );
    }
}
