//! Reference documentation for the expression-language functions.
//!
//! The canonical docs live as one Markdown file per function under
//! `docs/functions/` in this repository, arranged in one category subfolder
//! per function group (e.g. `Aggregation Functions/SUM.md`). They are
//! embedded into the library at compile time by this crate's build script
//! (`build.rs`), so [`function_docs`] never touches the disk: hosts get the
//! full reference instantly, packaged builds work without the source tree,
//! and the docs are always exactly as fresh as the engine build they ship
//! with. Editing a doc file triggers regeneration on the next build
//! (`cargo:rerun-if-changed`).

/// One function's reference documentation: the function name (the file stem,
/// e.g. `"DIVIDE"`), its category (the docs subfolder it lives in, e.g.
/// `"Conditional Functions"`), and its raw Markdown body.
#[derive(Debug, Clone)]
pub struct FunctionDoc {
    pub name: String,
    pub category: String,
    pub markdown: String,
}

// `FUNCTION_DOCS: &[(&str, &str, &str)]` — generated by build.rs from
// docs/functions.
include!(concat!(env!("OUT_DIR"), "/function_docs_generated.rs"));

/// Every embedded function doc, grouped by category — categories follow the
/// docs README's index order (unlisted ones sort after, alphabetically) —
/// and sorted by name within each category. The order is render-ready: hosts
/// build grouped reference sections by walking consecutive category runs.
pub fn function_docs() -> Vec<FunctionDoc> {
    FUNCTION_DOCS
        .iter()
        .map(|&(name, category, markdown)| FunctionDoc {
            name: name.to_string(),
            category: category.to_string(),
            markdown: markdown.to_string(),
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embeds_the_function_docs() {
        let docs = function_docs();
        assert!(!docs.is_empty(), "docs must be embedded at build time");
        let abs = docs
            .iter()
            .find(|d| d.name == "ABS")
            .expect("ABS.md present");
        assert!(abs.markdown.contains("# ABS"));
        assert_eq!(abs.category, "Math Functions", "category = docs subfolder");

        // Names sorted within each category.
        for pair in docs.windows(2) {
            if pair[0].category == pair[1].category {
                assert!(
                    pair[0].name < pair[1].name,
                    "names sorted within {:?}",
                    pair[0].category
                );
            }
        }

        // Each category is one contiguous run (grouped, never interleaved).
        let mut category_runs: Vec<&str> = Vec::new();
        for d in &docs {
            if category_runs.last() != Some(&d.category.as_str()) {
                assert!(
                    !category_runs.contains(&d.category.as_str()),
                    "category {:?} split into two runs",
                    d.category
                );
                category_runs.push(&d.category);
            }
        }

        // Categories follow the README index order, not the alphabet:
        // the README lists Statistical before Logical.
        let pos = |c: &str| category_runs.iter().position(|r| *r == c);
        let statistical = pos("Statistical Functions").expect("category present");
        let logical = pos("Logical Functions").expect("category present");
        assert!(
            statistical < logical,
            "categories must follow the README index order"
        );
    }
}
