//! FILENAME: app/src/core/theme/darkTheme.ts
// PURPOSE: Dark token baseline for the App Skin system. Mirrors EVERY key in
//          defaultTheme.ts (the light baseline) with dark-appropriate values.
// CONTEXT: Core/pure. Keep key-for-key in sync with defaultTheme.ts.

import { THEME_TOKENS } from "./tokens";

export const darkTheme: Record<string, string> = {
  // --- Context Menu ---
  [THEME_TOKENS.CTX_MENU_BG]: "#2d2d2d",
  [THEME_TOKENS.CTX_MENU_TEXT]: "#e0e0e0",
  [THEME_TOKENS.CTX_MENU_BORDER]: "#3a3a3a",
  [THEME_TOKENS.CTX_MENU_SHADOW]: "0 4px 12px rgba(0, 0, 0, 0.5)",
  [THEME_TOKENS.CTX_MENU_ITEM_HOVER_BG]: "#3a3a3a",
  [THEME_TOKENS.CTX_MENU_SEPARATOR]: "#3a3a3a",
  [THEME_TOKENS.CTX_MENU_Z_INDEX]: "10000",

  // --- Grid ---
  [THEME_TOKENS.GRID_BG]: "#1e1e1e",
  [THEME_TOKENS.GRID_TEXT]: "#e0e0e0",
  [THEME_TOKENS.GRID_LINE]: "#3a3a3a",
  [THEME_TOKENS.GRID_HEADER_BG]: "#252526",
  [THEME_TOKENS.GRID_HEADER_TEXT]: "#cccccc",
  [THEME_TOKENS.GRID_SELECTION_BORDER]: "#10b981",
  [THEME_TOKENS.GRID_SELECTION_BG]: "rgba(16, 185, 129, 0.18)",
  [THEME_TOKENS.SPREADSHEET_BG]: "#1e1e1e",
  [THEME_TOKENS.GRID_AREA_BG]: "#1e1e1e",
  [THEME_TOKENS.CANVAS_BG]: "#1e1e1e",

  // --- Formula Bar ---
  [THEME_TOKENS.FORMULA_BAR_BG]: "#252526",
  [THEME_TOKENS.FORMULA_BAR_BORDER]: "#3a3a3a",
  [THEME_TOKENS.FORMULA_BAR_BUTTON_BORDER]: "#3a3a3a",
  [THEME_TOKENS.FORMULA_BAR_BUTTON_DISABLED]: "#2d2d2d",
  [THEME_TOKENS.FORMULA_BAR_CANCEL_COLOR]: "#f87171",
  [THEME_TOKENS.FORMULA_BAR_ENTER_COLOR]: "#34d399",
  [THEME_TOKENS.FORMULA_BAR_FUNCTION_COLOR]: "#818cf8",
  [THEME_TOKENS.FORMULA_BAR_CANCEL_HOVER_BG]: "#3a2222",
  [THEME_TOKENS.FORMULA_BAR_ENTER_HOVER_BG]: "#1f3a2e",
  [THEME_TOKENS.FORMULA_BAR_FUNCTION_HOVER_BG]: "#262a45",
  [THEME_TOKENS.FORMULA_INPUT_BG]: "#1e1e1e",
  [THEME_TOKENS.FORMULA_INPUT_BG_FOCUSED]: "#252526",
  [THEME_TOKENS.FORMULA_INPUT_BORDER]: "#3a3a3a",
  [THEME_TOKENS.FORMULA_INPUT_TEXT]: "#e0e0e0",

  // --- Name Box ---
  [THEME_TOKENS.NAMEBOX_BG]: "#252526",
  [THEME_TOKENS.NAMEBOX_BG_EDITING]: "#3a3320",
  [THEME_TOKENS.NAMEBOX_BORDER]: "#3a3a3a",
  [THEME_TOKENS.NAMEBOX_TEXT]: "#e0e0e0",

  // --- Sheet Tabs ---
  [THEME_TOKENS.SHEET_TABS_BG]: "#252526",
  [THEME_TOKENS.SHEET_TABS_BORDER]: "#3a3a3a",
  [THEME_TOKENS.SHEET_TAB_BG]: "#323236",
  [THEME_TOKENS.SHEET_TAB_BORDER]: "#47474c",
  [THEME_TOKENS.SHEET_TAB_ACTIVE_BG]: "#1e1e1e",
  [THEME_TOKENS.SHEET_TAB_FORMULA_SOURCE_BG]: "#3a2e1a",
  [THEME_TOKENS.SHEET_TAB_FORMULA_SOURCE_BORDER]: "#ff9800",
  [THEME_TOKENS.SHEET_TAB_FORMULA_TARGET_BG]: "#1a2a3a",
  [THEME_TOKENS.SHEET_TAB_FORMULA_TARGET_BORDER]: "#2196f3",
  [THEME_TOKENS.SHEET_TAB_FORMULA_INDICATOR_TEXT]: "#64b5f6",
  [THEME_TOKENS.SHEET_TAB_FORMULA_INDICATOR_BG]: "#1a2a3a",

  // --- Dialog ---
  [THEME_TOKENS.DIALOG_OVERLAY_BG]: "rgba(0, 0, 0, 0.6)",
  [THEME_TOKENS.DIALOG_BG]: "#252526",
  [THEME_TOKENS.DIALOG_SHADOW]:
    "0 20px 25px -5px rgba(0, 0, 0, 0.5), 0 10px 10px -5px rgba(0, 0, 0, 0.3)",
  [THEME_TOKENS.DIALOG_BORDER]: "#3a3a3a",
  [THEME_TOKENS.DIALOG_TITLE_TEXT]: "#e0e0e0",
  [THEME_TOKENS.DIALOG_CLOSE_BUTTON]: "#9ca3af",
  [THEME_TOKENS.DIALOG_CLOSE_BUTTON_HOVER]: "#e0e0e0",
  [THEME_TOKENS.DIALOG_INPUT_BORDER]: "#3a3a3a",
  [THEME_TOKENS.DIALOG_INPUT_BG]: "#1e1e1e",
  [THEME_TOKENS.DIALOG_INPUT_TEXT]: "#e0e0e0",
  [THEME_TOKENS.DIALOG_INPUT_BORDER_FOCUS]: "#10b981",
  [THEME_TOKENS.DIALOG_CATEGORY_BORDER]: "#3a3a3a",
  [THEME_TOKENS.DIALOG_CATEGORY_BG]: "#252526",
  [THEME_TOKENS.DIALOG_CATEGORY_ACTIVE_BG]: "#10b981",
  [THEME_TOKENS.DIALOG_CATEGORY_TEXT]: "#9ca3af",
  [THEME_TOKENS.DIALOG_CATEGORY_ACTIVE_TEXT]: "#ffffff",
  [THEME_TOKENS.DIALOG_CATEGORY_HOVER_BG]: "#3a3a3a",
  [THEME_TOKENS.DIALOG_LOADING_TEXT]: "#9ca3af",
  [THEME_TOKENS.DIALOG_EMPTY_TEXT]: "#6b7280",
  [THEME_TOKENS.DIALOG_FUNCTION_SELECTED_BG]: "#1e3a5f",
  [THEME_TOKENS.DIALOG_FUNCTION_SELECTED_BORDER]: "#3b82f6",
  [THEME_TOKENS.DIALOG_FUNCTION_HOVER_BG]: "#3a3a3a",
  [THEME_TOKENS.DIALOG_FUNCTION_NAME]: "#60a5fa",
  [THEME_TOKENS.DIALOG_FUNCTION_DESCRIPTION]: "#9ca3af",
  [THEME_TOKENS.DIALOG_DETAILS_BG]: "#1e1e1e",
  [THEME_TOKENS.DIALOG_FUNCTION_SIGNATURE]: "#34d399",
  [THEME_TOKENS.DIALOG_FUNCTION_FULL_DESCRIPTION]: "#cccccc",
  [THEME_TOKENS.DIALOG_BUTTON_BORDER]: "#3a3a3a",
  [THEME_TOKENS.DIALOG_BUTTON_BG]: "#2d2d2d",
  [THEME_TOKENS.DIALOG_BUTTON_TEXT]: "#e0e0e0",
  [THEME_TOKENS.DIALOG_BUTTON_HOVER_BG]: "#3a3a3a",
  [THEME_TOKENS.DIALOG_INSERT_DISABLED_BG]: "#2d2d2d",
  [THEME_TOKENS.DIALOG_INSERT_BG]: "#10b981",
  [THEME_TOKENS.DIALOG_INSERT_TEXT]: "#ffffff",
  [THEME_TOKENS.DIALOG_INSERT_HOVER_BG]: "#059669",

  // --- Menu Bar ---
  [THEME_TOKENS.MENU_BAR_BG]: "#2d2d2d",
  [THEME_TOKENS.MENU_BAR_BORDER]: "#1e1e1e",
  [THEME_TOKENS.MENU_DROPDOWN_BG]: "#252526",
  [THEME_TOKENS.MENU_BORDER]: "#3a3a3a",
  [THEME_TOKENS.MENU_TEXT]: "#cccccc",
  [THEME_TOKENS.MENU_TEXT_DISABLED]: "#6c6c6c",
  [THEME_TOKENS.MENU_BUTTON_HOVER_BG]: "#3a3a3a",
  [THEME_TOKENS.MENU_BUTTON_ACTIVE_BG]: "#505050",
  [THEME_TOKENS.MENU_ITEM_HOVER_BG]: "#094771",
  [THEME_TOKENS.MENU_SHORTCUT_TEXT]: "#888888",
  [THEME_TOKENS.MENU_SEPARATOR]: "#3a3a3a",
  [THEME_TOKENS.MENU_SHADOW]: "rgba(0, 0, 0, 0.5)",

  // --- General ---
  [THEME_TOKENS.TEXT_PRIMARY]: "#e0e0e0",
  [THEME_TOKENS.TEXT_SECONDARY]: "#9ca3af",
  [THEME_TOKENS.TEXT_TERTIARY]: "#6b7280",
  [THEME_TOKENS.TEXT_ERROR]: "#f87171",
  [THEME_TOKENS.TEXT_DISABLED]: "#6b7280",
  [THEME_TOKENS.ACCENT_PRIMARY]: "#10b981",
  [THEME_TOKENS.ACCENT_COLOR]: "#3b82f6",
  [THEME_TOKENS.BG_SURFACE]: "#252526",
  [THEME_TOKENS.BG_SURFACE_DISABLED]: "#2d2d2d",
  [THEME_TOKENS.BORDER_DEFAULT]: "#3a3a3a",
  [THEME_TOKENS.BORDER_DISABLED]: "#2d2d2d",
  [THEME_TOKENS.PANEL_BG]: "#252526",
  [THEME_TOKENS.FONT_FAMILY_SANS]: "system-ui, -apple-system, sans-serif",
  // Cell/editor font (Excel default body font). Keeps the inline editor overlay
  // in the same family as the canvas cell text.
  [THEME_TOKENS.FONT_FAMILY_CELL]: 'Calibri, "Segoe UI", Arial, sans-serif',
  // px equivalent of the default 11pt cell text (11 * 96/72). Fallback for the
  // inline editor overlay when a cell carries no explicit size.
  [THEME_TOKENS.FONT_SIZE_CELL]: "14.667px",
  [THEME_TOKENS.Z_INDEX_EDITOR]: "10",

  // --- Scrollbar ---
  [THEME_TOKENS.SCROLLBAR_TRACK_BG]: "#1e1e1e",
  [THEME_TOKENS.SCROLLBAR_BORDER_COLOR]: "#3a3a3a",
  [THEME_TOKENS.SCROLLBAR_THUMB_BG_DEFAULT]: "#4a4a4a",
  [THEME_TOKENS.SCROLLBAR_THUMB_BG_HOVER]: "#5a5a5a",
  [THEME_TOKENS.SCROLLBAR_THUMB_BG_ACTIVE]: "#6a6a6a",
  [THEME_TOKENS.SCROLLBAR_THUMB_BORDER_COLOR]: "#3a3a3a",

  // --- Ribbon ---
  [THEME_TOKENS.RIBBON_BUTTON_ACTIVE_BG]: "rgba(255, 255, 255, 0.11)",
  [THEME_TOKENS.RIBBON_BUTTON_HOVER_BG]: "rgba(255, 255, 255, 0.07)",

  // --- Shared control atoms (@api/layout) ---
  [THEME_TOKENS.BUTTON_BG]: "transparent",
  [THEME_TOKENS.BUTTON_HOVER_BG]: "rgba(255, 255, 255, 0.08)",
  [THEME_TOKENS.BUTTON_ACTIVE_BG]: "rgba(255, 255, 255, 0.13)",
  // Pressed = accent tint: derived from --accent-primary so skin accent
  // overrides cascade to toggle states without retuning these.
  [THEME_TOKENS.BUTTON_PRESSED_BG]: "color-mix(in srgb, var(--accent-primary) 28%, transparent)",
  [THEME_TOKENS.BUTTON_PRESSED_BORDER]: "color-mix(in srgb, var(--accent-primary) 55%, transparent)",
};
