import { THEME_TOKENS } from './tokens';

export const defaultTheme: Record<string, string> = {
  // --- Context Menu ---
  [THEME_TOKENS.CTX_MENU_BG]: '#ffffff',
  [THEME_TOKENS.CTX_MENU_TEXT]: '#333333',
  [THEME_TOKENS.CTX_MENU_BORDER]: '#d1d5db',
  [THEME_TOKENS.CTX_MENU_HOVER_BG]: '#f3f4f6',
  [THEME_TOKENS.CTX_MENU_SEPARATOR]: '#e5e7eb',

  // --- Grid ---
  [THEME_TOKENS.GRID_BG]: '#ffffff',
  [THEME_TOKENS.GRID_TEXT]: '#000000',
  [THEME_TOKENS.GRID_LINE]: '#e0e0e0',
  [THEME_TOKENS.GRID_HEADER_BG]: '#f9fafb',
  [THEME_TOKENS.GRID_HEADER_TEXT]: '#374151',
  [THEME_TOKENS.GRID_SELECTION_BORDER]: '#10b981',
  [THEME_TOKENS.GRID_SELECTION_BG]: 'rgba(16, 185, 129, 0.1)',
  [THEME_TOKENS.SPREADSHEET_BG]: '#ffffff',
  [THEME_TOKENS.GRID_AREA_BG]: '#ffffff',
  [THEME_TOKENS.CANVAS_BG]: '#ffffff',

  // --- Formula Bar ---
  [THEME_TOKENS.FORMULA_BAR_BG]: '#ffffff',
  [THEME_TOKENS.FORMULA_BAR_BORDER]: '#d1d5db',
  [THEME_TOKENS.FORMULA_INPUT_BG]: '#ffffff',

  // --- Menu Bar ---
  [THEME_TOKENS.MENU_BAR_BG]: '#3c3c3c',
  [THEME_TOKENS.MENU_BAR_BORDER]: '#252526',
  [THEME_TOKENS.MENU_DROPDOWN_BG]: '#252526',
  [THEME_TOKENS.MENU_BORDER]: '#454545',
  [THEME_TOKENS.MENU_TEXT]: '#cccccc',
  [THEME_TOKENS.MENU_TEXT_DISABLED]: '#6c6c6c',
  [THEME_TOKENS.MENU_BUTTON_HOVER_BG]: '#454545',
  [THEME_TOKENS.MENU_BUTTON_ACTIVE_BG]: '#505050',
  [THEME_TOKENS.MENU_ITEM_HOVER_BG]: '#094771',
  [THEME_TOKENS.MENU_SHORTCUT_TEXT]: '#888888',
  [THEME_TOKENS.MENU_SEPARATOR]: '#454545',
  [THEME_TOKENS.MENU_SHADOW]: 'rgba(0, 0, 0, 0.3)',

  // --- General ---
  [THEME_TOKENS.TEXT_PRIMARY]: '#111827',
  [THEME_TOKENS.TEXT_SECONDARY]: '#6b7280',
  [THEME_TOKENS.TEXT_DISABLED]: '#9ca3af',
  [THEME_TOKENS.ACCENT_PRIMARY]: '#10b981',
  [THEME_TOKENS.ACCENT_COLOR]: '#1a5fb4',
  [THEME_TOKENS.BG_SURFACE]: '#ffffff',
  [THEME_TOKENS.BG_SURFACE_DISABLED]: '#f5f5f5',
  [THEME_TOKENS.BORDER_DEFAULT]: '#d1d5db',
  [THEME_TOKENS.BORDER_DISABLED]: '#e5e7eb',
  [THEME_TOKENS.PANEL_BG]: '#f9fafb',
  [THEME_TOKENS.FONT_FAMILY_SANS]: 'system-ui, -apple-system, sans-serif',
  [THEME_TOKENS.FONT_SIZE_CELL]: '13px',
  [THEME_TOKENS.Z_INDEX_EDITOR]: '10',

  // --- Scrollbar ---
  [THEME_TOKENS.SCROLLBAR_TRACK_BG]: '#f5f5f5',
  [THEME_TOKENS.SCROLLBAR_BORDER_COLOR]: '#d1d5db',
  [THEME_TOKENS.SCROLLBAR_THUMB_BG_DEFAULT]: '#c0c0c0',
  [THEME_TOKENS.SCROLLBAR_THUMB_BG_HOVER]: '#a0a0a0',
  [THEME_TOKENS.SCROLLBAR_THUMB_BG_ACTIVE]: '#808080',
  [THEME_TOKENS.SCROLLBAR_THUMB_BORDER_COLOR]: '#d1d5db',
};