/**
 * These are the semantic keys for your application.
 * Extensions will eventually be able to override the values of these variables.
 */
export const THEME_TOKENS = {
  // --- Context Menu ---
  CTX_MENU_BG: '--ctx-menu-bg',
  CTX_MENU_TEXT: '--ctx-menu-text',
  CTX_MENU_BORDER: '--ctx-menu-border',
  CTX_MENU_HOVER_BG: '--ctx-menu-hover-bg',
  CTX_MENU_SEPARATOR: '--ctx-menu-separator',

  // --- Grid / Spreadsheet ---
  GRID_BG: '--grid-bg',
  GRID_TEXT: '--grid-text',
  GRID_LINE: '--grid-line',
  GRID_HEADER_BG: '--grid-header-bg',
  GRID_HEADER_TEXT: '--grid-header-text',
  GRID_SELECTION_BORDER: '--grid-selection-border',
  GRID_SELECTION_BG: '--grid-selection-bg',
  SPREADSHEET_BG: '--spreadsheet-bg',
  GRID_AREA_BG: '--grid-area-bg',
  CANVAS_BG: '--canvas-bg',

  // --- Formula Bar ---
  FORMULA_BAR_BG: '--formula-bar-bg',
  FORMULA_BAR_BORDER: '--formula-bar-border',
  FORMULA_BAR_BUTTON_BORDER: '--formula-bar-button-border',
  FORMULA_BAR_BUTTON_DISABLED: '--formula-bar-button-disabled',
  FORMULA_BAR_CANCEL_COLOR: '--formula-bar-cancel-color',
  FORMULA_BAR_ENTER_COLOR: '--formula-bar-enter-color',
  FORMULA_BAR_FUNCTION_COLOR: '--formula-bar-function-color',
  FORMULA_BAR_CANCEL_HOVER_BG: '--formula-bar-cancel-hover-bg',
  FORMULA_BAR_ENTER_HOVER_BG: '--formula-bar-enter-hover-bg',
  FORMULA_BAR_FUNCTION_HOVER_BG: '--formula-bar-function-hover-bg',
  FORMULA_INPUT_BG: '--formula-input-bg',
  FORMULA_INPUT_BG_FOCUSED: '--formula-input-bg-focused',
  FORMULA_INPUT_BORDER: '--formula-input-border',
  FORMULA_INPUT_TEXT: '--formula-input-text',

  // --- Name Box ---
  NAMEBOX_BG: '--namebox-bg',
  NAMEBOX_BG_EDITING: '--namebox-bg-editing',
  NAMEBOX_BORDER: '--namebox-border',
  NAMEBOX_TEXT: '--namebox-text',

  // --- Dialog ---
  DIALOG_OVERLAY_BG: '--dialog-overlay-bg',
  DIALOG_BG: '--dialog-bg',
  DIALOG_SHADOW: '--dialog-shadow',
  DIALOG_BORDER: '--dialog-border',
  DIALOG_TITLE_TEXT: '--dialog-title-text',
  DIALOG_CLOSE_BUTTON: '--dialog-close-button',
  DIALOG_CLOSE_BUTTON_HOVER: '--dialog-close-button-hover',
  DIALOG_INPUT_BORDER: '--dialog-input-border',
  DIALOG_INPUT_BG: '--dialog-input-bg',
  DIALOG_INPUT_TEXT: '--dialog-input-text',
  DIALOG_INPUT_BORDER_FOCUS: '--dialog-input-border-focus',
  DIALOG_CATEGORY_BORDER: '--dialog-category-border',
  DIALOG_CATEGORY_BG: '--dialog-category-bg',
  DIALOG_CATEGORY_ACTIVE_BG: '--dialog-category-active-bg',
  DIALOG_CATEGORY_TEXT: '--dialog-category-text',
  DIALOG_CATEGORY_ACTIVE_TEXT: '--dialog-category-active-text',
  DIALOG_CATEGORY_HOVER_BG: '--dialog-category-hover-bg',
  DIALOG_LOADING_TEXT: '--dialog-loading-text',
  DIALOG_EMPTY_TEXT: '--dialog-empty-text',
  DIALOG_FUNCTION_SELECTED_BG: '--dialog-function-selected-bg',
  DIALOG_FUNCTION_SELECTED_BORDER: '--dialog-function-selected-border',
  DIALOG_FUNCTION_HOVER_BG: '--dialog-function-hover-bg',
  DIALOG_FUNCTION_NAME: '--dialog-function-name',
  DIALOG_FUNCTION_DESCRIPTION: '--dialog-function-description',
  DIALOG_DETAILS_BG: '--dialog-details-bg',
  DIALOG_FUNCTION_SIGNATURE: '--dialog-function-signature',
  DIALOG_FUNCTION_FULL_DESCRIPTION: '--dialog-function-full-description',
  DIALOG_BUTTON_BORDER: '--dialog-button-border',
  DIALOG_BUTTON_BG: '--dialog-button-bg',
  DIALOG_BUTTON_TEXT: '--dialog-button-text',
  DIALOG_BUTTON_HOVER_BG: '--dialog-button-hover-bg',
  DIALOG_INSERT_DISABLED_BG: '--dialog-insert-disabled-bg',
  DIALOG_INSERT_BG: '--dialog-insert-bg',
  DIALOG_INSERT_TEXT: '--dialog-insert-text',
  DIALOG_INSERT_HOVER_BG: '--dialog-insert-hover-bg',

  // --- Menu Bar ---
  MENU_BAR_BG: '--menu-bar-bg',
  MENU_BAR_BORDER: '--menu-bar-border',
  MENU_DROPDOWN_BG: '--menu-dropdown-bg',
  MENU_BORDER: '--menu-border',
  MENU_TEXT: '--menu-text',
  MENU_TEXT_DISABLED: '--menu-text-disabled',
  MENU_BUTTON_HOVER_BG: '--menu-button-hover-bg',
  MENU_BUTTON_ACTIVE_BG: '--menu-button-active-bg',
  MENU_ITEM_HOVER_BG: '--menu-item-hover-bg',
  MENU_SHORTCUT_TEXT: '--menu-shortcut-text',
  MENU_SEPARATOR: '--menu-separator',
  MENU_SHADOW: '--menu-shadow',

  // --- General UI ---
  TEXT_PRIMARY: '--text-primary',
  TEXT_SECONDARY: '--text-secondary',
  TEXT_DISABLED: '--text-disabled',
  ACCENT_PRIMARY: '--accent-primary',
  ACCENT_COLOR: '--accent-color',
  BG_SURFACE: '--bg-surface',
  BG_SURFACE_DISABLED: '--bg-surface-disabled',
  BORDER_DEFAULT: '--border-default',
  BORDER_DISABLED: '--border-disabled',
  PANEL_BG: '--panel-bg',
  FONT_FAMILY_SANS: '--font-family-sans',
  FONT_SIZE_CELL: '--font-size-cell',
  Z_INDEX_EDITOR: '--z-index-editor',

  // --- Scrollbar ---
  SCROLLBAR_TRACK_BG: '--scrollbar-track-bg',
  SCROLLBAR_BORDER_COLOR: '--scrollbar-border-color',
  SCROLLBAR_THUMB_BG_DEFAULT: '--scrollbar-thumb-bg-default',
  SCROLLBAR_THUMB_BG_HOVER: '--scrollbar-thumb-bg-hover',
  SCROLLBAR_THUMB_BG_ACTIVE: '--scrollbar-thumb-bg-active',
  SCROLLBAR_THUMB_BORDER_COLOR: '--scrollbar-thumb-border-color',
} as const;