//! Function catalog generated from `docs/functions/**/*.md` at build time.
//!
//! Provides metadata (name, description, signature) for every expression
//! language function, suitable for driving IDE features like autocomplete,
//! signature help, and hover documentation.

/// Metadata for a single expression language function.
#[derive(Debug, Clone)]
pub struct FunctionInfo {
    /// Canonical name, e.g. `"SUM"`.
    pub name: &'static str,
    /// One-line description from the function's documentation.
    pub description: &'static str,
    /// Syntax signature, e.g. `"SUM(table[column])"`.
    pub signature: &'static str,
}

include!(concat!(env!("OUT_DIR"), "/function_catalog_generated.rs"));

/// Returns the complete function catalog, sorted alphabetically by name.
pub fn function_catalog() -> &'static [FunctionInfo] {
    CATALOG
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The catalog is GENERATED by `build.rs` from `docs/functions/**/*.md`, and
    /// that build script is deliberately non-fatal: when the docs directory
    /// cannot be read it prints a warning and writes
    /// `static CATALOG: &[FunctionInfo] = &[];`, so the build stays GREEN with an
    /// empty catalog while every consumer — autocomplete, signature help, hover —
    /// silently has nothing to offer. A warning on stderr is not a gate; nobody
    /// reads a green job's log.
    ///
    /// The sibling embed one crate over (`engine::function_docs`) has always
    /// asserted `!docs.is_empty()`. This one asserted nothing, which is the whole
    /// reason for this test — and it matters more now that CI runs this
    /// workspace, because without it a broken docs path is a PASSING build.
    #[test]
    fn the_catalog_is_generated_from_the_docs_and_is_not_empty() {
        let catalog = function_catalog();

        assert!(
            !catalog.is_empty(),
            "empty catalog — build.rs could not read docs/functions and fell back \
             to an empty CATALOG without failing the build"
        );

        // A floor, not a pin: functions get added and this test must not become a
        // chore that gets edited on autopilot. 152 function docs exist today; a
        // count anywhere near zero means the generator parsed almost nothing.
        assert!(
            catalog.len() >= 100,
            "catalog holds only {} entries; docs/functions carries ~152 function \
             files, so the generator parsed almost none of them",
            catalog.len()
        );

        // Non-empty is not the same as PARSED. Pin one function end to end so a
        // generator that emits rows of blanks cannot pass.
        let abs = catalog
            .iter()
            .find(|f| f.name == "ABS")
            .expect("ABS is documented at docs/functions/Math Functions/ABS.md");
        assert_eq!(abs.signature, "ABS(expression)");
        assert!(
            abs.description.starts_with("Returns the absolute value"),
            "description came from the wrong line: {:?}",
            abs.description
        );

        // build.rs advertises the LONGEST call variant, not the first one listed,
        // so a function whose doc opens with the bare form still gets the fullest
        // signature. SUM.md lists `SUM(table[column])` before the context form.
        let sum = catalog
            .iter()
            .find(|f| f.name == "SUM")
            .expect("SUM is documented");
        assert_eq!(
            sum.signature, "SUM(table[column], context_op1, context_op2, ...)",
            "the fullest variant must win, not the first one listed"
        );

        // Sorted by name — build.rs sorts before emitting, and the doc comment on
        // `function_catalog` promises callers it is sorted.
        for pair in catalog.windows(2) {
            assert!(
                pair[0].name < pair[1].name,
                "catalog must be sorted by name: {:?} precedes {:?}",
                pair[0].name,
                pair[1].name
            );
        }

        // No entry may be half-parsed. A doc whose shape the generator does not
        // understand yields blank fields rather than an error, so the blank is
        // the only symptom there will ever be.
        for f in catalog {
            assert!(!f.name.is_empty(), "an entry has no name");
            assert!(!f.description.is_empty(), "{} has no description", f.name);
            assert!(!f.signature.is_empty(), "{} has no signature", f.name);
        }
    }
}
