//! FILENAME: app/src/shell/utils/mockData.csv.ts
// PURPOSE: Mock CSV data for development and testing
// DELETE THIS FILE: This file contains test data and should be removed when done testing

/**
 * Sample CSV data - Swedish names and cities
 * This data is used only for development/testing purposes.
 * To remove mock data feature, delete this file and mockData.ts.
 */
export const MOCK_CSV_DATA = `first_name,last_name,gender,city,sales
Erik,Johansson,Male,Stockholm,452
Erik,Andersson,Male,Uppsala,819
Erik,Karlsson,Male,Gothenburg,234
Erik,Nilsson,Male,Stockholm,912
Erik,Eriksson,Male,Uppsala,567
Erik,Larsson,Male,Gothenburg,104
Erik,Olsson,Male,Stockholm,789
Erik,Persson,Male,Uppsala,345
Erik,Svensson,Male,Gothenburg,621
Erik,Gustafsson,Male,Stockholm,890
Lars,Johansson,Male,Uppsala,156
Lars,Andersson,Male,Gothenburg,982
Lars,Karlsson,Male,Stockholm,431
Lars,Nilsson,Male,Uppsala,765
Lars,Eriksson,Male,Gothenburg,298
Lars,Larsson,Male,Stockholm,543
Lars,Olsson,Male,Uppsala,876
Lars,Persson,Male,Gothenburg,123
Lars,Svensson,Male,Stockholm,654
Lars,Gustafsson,Male,Uppsala,321
Karl,Johansson,Male,Gothenburg,870
Karl,Andersson,Male,Stockholm,512
Karl,Karlsson,Male,Uppsala,245
Karl,Nilsson,Male,Gothenburg,934
Karl,Eriksson,Male,Stockholm,167
Karl,Larsson,Male,Uppsala,678
Karl,Olsson,Male,Gothenburg,349
Karl,Persson,Male,Stockholm,812
Karl,Svensson,Male,Uppsala,456
Karl,Gustafsson,Male,Gothenburg,901
Anders,Johansson,Male,Stockholm,238
Anders,Andersson,Male,Uppsala,784
Anders,Karlsson,Male,Gothenburg,195
Anders,Nilsson,Male,Stockholm,642
Anders,Eriksson,Male,Uppsala,853
Anders,Larsson,Male,Gothenburg,316
Anders,Olsson,Male,Stockholm,971
Anders,Persson,Male,Uppsala,420
Anders,Svensson,Male,Gothenburg,539
Anders,Gustafsson,Male,Stockholm,708
Johan,Johansson,Male,Uppsala,147
Johan,Andersson,Male,Gothenburg,862
Johan,Karlsson,Male,Stockholm,395
Johan,Nilsson,Male,Uppsala,951
Johan,Eriksson,Male,Gothenburg,584
Johan,Larsson,Male,Stockholm,217
Johan,Olsson,Male,Uppsala,730
Johan,Persson,Male,Gothenburg,463
Johan,Svensson,Male,Stockholm,896
Johan,Gustafsson,Male,Uppsala,329
Per,Johansson,Male,Gothenburg,685
Per,Andersson,Male,Stockholm,152
Per,Karlsson,Male,Uppsala,948
Per,Nilsson,Male,Gothenburg,415
Per,Eriksson,Male,Stockholm,872
Per,Larsson,Male,Uppsala,369
Per,Olsson,Male,Gothenburg,753
Per,Persson,Male,Stockholm,286
Per,Svensson,Male,Uppsala,914
Per,Gustafsson,Male,Gothenburg,507
Nils,Johansson,Male,Stockholm,831
Nils,Andersson,Male,Uppsala,264
Nils,Karlsson,Male,Gothenburg,798
Nils,Nilsson,Male,Stockholm,135
Nils,Eriksson,Male,Uppsala,602
Nils,Larsson,Male,Gothenburg,967
Nils,Olsson,Male,Stockholm,480
Nils,Persson,Male,Uppsala,823
Nils,Svensson,Male,Gothenburg,356
Nils,Gustafsson,Male,Stockholm,519
Carl,Johansson,Male,Uppsala,974
Carl,Andersson,Male,Gothenburg,427
Carl,Karlsson,Male,Stockholm,860
Carl,Nilsson,Male,Uppsala,193
Carl,Eriksson,Male,Gothenburg,746
Carl,Larsson,Male,Stockholm,589
Carl,Olsson,Male,Uppsala,312
Carl,Persson,Male,Gothenburg,905
Carl,Svensson,Male,Stockholm,638
Carl,Gustafsson,Male,Uppsala,271
Mikael,Johansson,Male,Gothenburg,504
Mikael,Andersson,Male,Stockholm,847
Mikael,Karlsson,Male,Uppsala,380
Mikael,Nilsson,Male,Gothenburg,923
Mikael,Eriksson,Male,Stockholm,166
Mikael,Larsson,Male,Uppsala,719
Mikael,Olsson,Male,Gothenburg,452
Mikael,Persson,Male,Stockholm,885
Mikael,Svensson,Male,Uppsala,228
Mikael,Gustafsson,Male,Gothenburg,671
Jan,Johansson,Male,Stockholm,918
Jan,Andersson,Male,Uppsala,341
Jan,Karlsson,Male,Gothenburg,784
Jan,Nilsson,Male,Stockholm,527
Jan,Eriksson,Male,Uppsala,170
Jan,Larsson,Male,Gothenburg,803
Jan,Olsson,Male,Stockholm,436
Jan,Persson,Male,Uppsala,969
Jan,Svensson,Male,Gothenburg,292
Jan,Gustafsson,Male,Stockholm,645
Maria,Johansson,Female,Uppsala,378
Maria,Andersson,Female,Gothenburg,811
Maria,Karlsson,Female,Stockholm,554
Maria,Nilsson,Female,Uppsala,187
Maria,Eriksson,Female,Gothenburg,930
Maria,Larsson,Female,Stockholm,463
Maria,Olsson,Female,Uppsala,706
Maria,Persson,Female,Gothenburg,249
Maria,Svensson,Female,Stockholm,892
Maria,Gustafsson,Female,Uppsala,625
Anna,Johansson,Female,Gothenburg,158
Anna,Andersson,Female,Stockholm,791
Anna,Karlsson,Female,Uppsala,424
Anna,Nilsson,Female,Gothenburg,967
Anna,Eriksson,Female,Stockholm,310
Anna,Larsson,Female,Uppsala,853
Anna,Olsson,Female,Gothenburg,586
Anna,Persson,Female,Stockholm,129
Anna,Svensson,Female,Uppsala,672
Anna,Gustafsson,Female,Gothenburg,905
Margareta,Johansson,Female,Stockholm,448
Margareta,Andersson,Female,Uppsala,881
Margareta,Karlsson,Female,Gothenburg,214
Margareta,Nilsson,Female,Stockholm,757
Margareta,Eriksson,Female,Uppsala,500
Margareta,Larsson,Female,Gothenburg,943
Margareta,Olsson,Female,Stockholm,386
Margareta,Persson,Female,Uppsala,829
Margareta,Svensson,Female,Gothenburg,162
Margareta,Gustafsson,Female,Stockholm,615
Elisabeth,Johansson,Female,Uppsala,958
Elisabeth,Andersson,Female,Gothenburg,291
Elisabeth,Karlsson,Female,Stockholm,834
Elisabeth,Nilsson,Female,Uppsala,477
Elisabeth,Eriksson,Female,Gothenburg,720
Elisabeth,Larsson,Female,Stockholm,153
Elisabeth,Olsson,Female,Uppsala,696
Elisabeth,Persson,Female,Gothenburg,539
Elisabeth,Svensson,Female,Stockholm,982
Elisabeth,Gustafsson,Female,Uppsala,325
Eva,Johansson,Female,Gothenburg,768
Eva,Andersson,Female,Stockholm,101
Eva,Karlsson,Female,Uppsala,644
Eva,Nilsson,Female,Gothenburg,887
Eva,Eriksson,Female,Stockholm,430
Eva,Larsson,Female,Uppsala,973
Eva,Olsson,Female,Gothenburg,216
Eva,Persson,Female,Stockholm,559
Eva,Svensson,Female,Uppsala,802
Eva,Gustafsson,Female,Gothenburg,345
Kristina,Johansson,Female,Stockholm,898
Kristina,Andersson,Female,Uppsala,431
Kristina,Karlsson,Female,Gothenburg,974
Kristina,Nilsson,Female,Stockholm,207
Kristina,Eriksson,Female,Uppsala,650
Kristina,Larsson,Female,Gothenburg,183
Kristina,Olsson,Female,Stockholm,726
Kristina,Persson,Female,Uppsala,569
Kristina,Svensson,Female,Gothenburg,912
Kristina,Gustafsson,Female,Stockholm,355
Birgitta,Johansson,Female,Uppsala,608
Birgitta,Andersson,Female,Gothenburg,141
Birgitta,Karlsson,Female,Stockholm,884
Birgitta,Nilsson,Female,Uppsala,317
Birgitta,Eriksson,Female,Gothenburg,570
Birgitta,Larsson,Female,Stockholm,913
Birgitta,Olsson,Female,Uppsala,456
Birgitta,Persson,Female,Gothenburg,799
Birgitta,Svensson,Female,Stockholm,232
Birgitta,Gustafsson,Female,Uppsala,675
Karin,Johansson,Female,Gothenburg,928
Karin,Andersson,Female,Stockholm,361
Karin,Karlsson,Female,Uppsala,804
Karin,Nilsson,Female,Gothenburg,137
Karin,Eriksson,Female,Stockholm,680
Karin,Larsson,Female,Uppsala,423
Karin,Olsson,Female,Gothenburg,866
Karin,Persson,Female,Stockholm,509
Karin,Svensson,Female,Uppsala,952
Karin,Gustafsson,Female,Gothenburg,285
Marie,Johansson,Female,Stockholm,738
Marie,Andersson,Female,Uppsala,171
Marie,Karlsson,Female,Gothenburg,614
Marie,Nilsson,Female,Stockholm,957
Marie,Eriksson,Female,Uppsala,390
Marie,Larsson,Female,Gothenburg,833
Marie,Olsson,Female,Stockholm,276
Marie,Persson,Female,Uppsala,719
Marie,Svensson,Female,Gothenburg,152
Marie,Gustafsson,Female,Stockholm,595
Ingrid,Johansson,Female,Uppsala,848
Ingrid,Andersson,Female,Gothenburg,481
Ingrid,Karlsson,Female,Stockholm,924
Ingrid,Nilsson,Female,Uppsala,267
Ingrid,Eriksson,Female,Gothenburg,710
Ingrid,Larsson,Female,Stockholm,143
Ingrid,Olsson,Female,Uppsala,586
Ingrid,Persson,Female,Gothenburg,939
Ingrid,Svensson,Female,Stockholm,372
Ingrid,Gustafsson,Female,Uppsala,815`;
