/**
 * TELL DROPBOX TO LEAVE THE BUILD TREES ALONE.
 *
 * ===========================================================================
 * THIS IS NOT HOUSEKEEPING. IT IS A MEASURED CAUSE OF FAILED TEST RUNS.
 * ===========================================================================
 * The whole repository lives under `C:\Dropbox\...`, so Dropbox opens every file
 * anything writes here in order to index and upload it. Two of the trees that
 * churn hardest were already protected with the `com.dropbox.ignored` alternate
 * data stream -- `app/src-tauri/target` (100,175 files) and `core/target`. One
 * was NOT: `app/node_modules` (18,810 files), which contains Vite's dependency
 * cache.
 *
 * Vite pre-bundles dependencies into `node_modules/.vite/deps_temp_<hash>/` and
 * then RENAMES that directory onto `deps/`. A rename fails outright if anything
 * holds a handle inside it. Measured 2026-08-15, cache cleared, optimiser run in
 * a loop:
 *
 *     WITHOUT the marker   3 of 10 runs failed with
 *                            EBUSY: resource busy or locked, rename
 *                              '...\.vite\deps_temp_78efe380' -> '...\.vite\deps'
 *     WITH the marker      1 of 12
 *
 * A failed rename leaves no usable `deps/`, so the dev server discovers
 * dependencies while the page is already loading and serves `react.js` under
 * more than one `?v=` hash -- more than one React, `Invalid hook call`, a window
 * that never renders. Under E2E (`CALCULA_E2E=1`, HMR off) Vite's own repair is
 * disconnected, so it never recovers: BUG-0082's second mechanism, and it reads
 * as N product failures. See app/scripts/ensure-dep-cache.mjs.
 *
 * The marker is an NTFS alternate data stream, so it CANNOT live in git: it is
 * per-machine state, and a fresh clone or a fresh `npm install` starts without
 * it. That is why this is a script that can be re-run at any time, and why
 * `e2e/__tests__/dropboxIgnoreMarkers.test.ts` fails when the trees it names are
 * unprotected on THIS machine.
 *
 * Marking a folder ignored stops Dropbox syncing it and removes it from the
 * cloud; the local files are untouched. Everything listed below is either
 * regenerated by a build (`target`, `dist`, `node_modules`) or is test output.
 * Nothing here is a source file or a golden.
 *
 *   node scripts/dropbox-ignore.mjs           apply, then report
 *   node scripts/dropbox-ignore.mjs --check   report only, exit 1 if unprotected
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const APP_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const REPO_DIR = path.resolve(APP_DIR, "..");

/**
 * Trees Dropbox must not touch, relative to the repository root -- the ones that
 * are LONG-LIVED, so a missing marker is a real defect rather than a race.
 *
 * ORDERED BY MEASURED HARM. The first entry is the one that was missing and cost
 * a 36 %-of-cold-launches E2E collapse; the rest are the same shape of hazard
 * (huge, machine-generated, rewritten constantly) and are listed so a fresh
 * machine gets all of them from one command.
 *
 * These are what `--check` and `e2e/__tests__/depCacheWired.test.ts` ASSERT on.
 */
export const DROPBOX_IGNORED_TREES = [
  // Vite's dependency cache lives in here. THE measured one.
  "app/node_modules",
  // npm's root install, same reasoning.
  "node_modules",
  // Already marked on this machine; listed so a fresh clone gets them too.
  "app/src-tauri/target",
  "core/target",
  "model-engine-lib/target",
];

/**
 * Output trees. Marked when they exist, and DELIBERATELY NOT ASSERTED.
 *
 * An alternate data stream belongs to the directory, so it dies with it -- and
 * Playwright deletes and recreates `test-results/` inside its own run. Asserting
 * on these would produce a guard that goes red for a reason nobody caused, and a
 * guard that cries wolf is a guard that gets switched off. (Found the honest
 * way: the assertion caught `app/test-results` seconds after a vitest run had
 * recreated it.) They are still worth marking -- it is free -- but the fact they
 * carry is "someone ran the script recently", not "the machine is misconfigured".
 */
export const DROPBOX_IGNORED_OUTPUT_TREES = [
  "app/dist",
  "app/test-results",
  "app/playwright-report",
  "app/e2e/results",
  // Fetched, never authored: the bundled inference runtime (~20 MB per
  // architecture) and the on-board model (1.1 GB). The fetch scripts mark
  // these themselves the moment they create them, so a 1 GB model file never
  // starts uploading; listed here so a re-run of this script covers them too.
  "app/src-tauri/binaries",
  "app/src-tauri/models",
];

const STREAM = "com.dropbox.ignored";

/** Is this tree currently marked? `null` when the directory does not exist. */
export function isIgnored(absDir) {
  if (!fs.existsSync(absDir)) return null;
  try {
    return fs.readFileSync(`${absDir}:${STREAM}`, "utf8").trim() === "1";
  } catch {
    return false;
  }
}

/** Mark one tree. Returns what happened; never throws. */
export function markIgnored(absDir) {
  if (!fs.existsSync(absDir)) return "missing";
  if (isIgnored(absDir)) return "already";
  try {
    fs.writeFileSync(`${absDir}:${STREAM}`, "1");
    return isIgnored(absDir) ? "marked" : "failed";
  } catch (err) {
    return `failed (${err instanceof Error ? err.message : String(err)})`;
  }
}

/**
 * Every LONG-LIVED tree with its current state. Used by the script AND by the
 * test, which is why it deliberately excludes the output directories: those get
 * deleted and recreated by test runs, taking their marker with them.
 */
export function surveyIgnoredTrees(repoRoot = REPO_DIR) {
  return DROPBOX_IGNORED_TREES.map((rel) => {
    const abs = path.join(repoRoot, rel.replace(/\//g, path.sep));
    return { rel, abs, exists: fs.existsSync(abs), ignored: isIgnored(abs) };
  });
}

// --- CLI ---------------------------------------------------------------------
if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const checkOnly = process.argv.includes("--check");
  let unprotected = 0;
  for (const rel of [...DROPBOX_IGNORED_TREES, ...DROPBOX_IGNORED_OUTPUT_TREES]) {
    // Only the long-lived trees count towards the exit status; an output
    // directory that a test run has just recreated is not a misconfiguration.
    const counts = DROPBOX_IGNORED_TREES.includes(rel);
    const abs = path.join(REPO_DIR, rel.replace(/\//g, path.sep));
    if (!fs.existsSync(abs)) {
      console.log(`[dropbox] ${rel.padEnd(28)} (not present)`);
      continue;
    }
    if (checkOnly) {
      const ok = isIgnored(abs);
      if (!ok && counts) unprotected++;
      console.log(
        `[dropbox] ${rel.padEnd(28)} ${ok ? "ignored" : counts ? "NOT IGNORED" : "not ignored (output)"}`,
      );
      continue;
    }
    const outcome = markIgnored(abs);
    if (outcome.startsWith("failed") && counts) unprotected++;
    console.log(`[dropbox] ${rel.padEnd(28)} ${outcome}`);
  }
  if (unprotected > 0) {
    console.log(
      `\n[dropbox] ${unprotected} tree(s) are still synced. Dropbox holds handles on files` +
        " the moment they are written, which makes Vite's dependency-cache rename fail with" +
        " EBUSY and hands the app more than one copy of React (BUG-0082, open-decisions §32).",
    );
  }
  process.exit(checkOnly && unprotected > 0 ? 1 : 0);
}
